# Stage 1: Build
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./

# Add --include=dev to ensure the Angular CLI (ng) is installed
RUN npm install --include=dev --no-audit --no-fund

COPY . .

# Use the absolute path to the local ng tool
RUN ./node_modules/.bin/ng build --configuration production

# Stage 2: Serve
FROM nginx:alpine
# Copy the browser folder generated by Angular 21
COPY --from=build /app/dist/edu-stream/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]