services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: . # Point to your new Node.js folder
      dockerfile: ./server/Dockerfile.server
    ports:
      - "5000:5000" # Map Docker port 5000 to Node's port 5000
    environment:
      - MONGO_URI=mongodb://mongo:27017/edustream
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}